name: Build
on:
  push:
    branches:
      - main

jobs:
  Build:
    name: Build and Upload
    runs-on: windows-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v1

      - name: Build
        shell: cmd
        run: build.bat

      - name: Upload Binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: chrome-temp.zip
          repo_name: ChromeTemp
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          body: To use ChromeTemp, download chrome-temp.zip, unpack where you want and run RUNME.bat
