name: Build
on:
  push:
    branches:
      - main

jobs:
  Build:
    name: Build and Upload
    runs-on: windows-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v1

      - name: Build
        shell: cmd
        run: build.bat

      - name: Upload and release
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: chrome-temp.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
