name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name to release'
        default: 'v1.0.0'
        required: true
      releaseContent:
        description: 'Content of the release (ex. changelog, how-to run)'
        default: 'To use ChromeTemp, download chrome-temp.zip, unpack where you want and run RUNME.bat'
        required: true

jobs:
  Build:
    name: Build and Upload
    runs-on: windows-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v1

      - name: Build
        shell: cmd
        run: build.bat ${{ github.event.inputs.version }}

      - name: Upload Binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: chrome-temp.zip
          release_name: 'ChromeTemp ${{ github.event.inputs.version }}'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.releaseContent }}
