name: Build
on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: windows-latest
    steps:
    - name: Build
      shell: cmd
      run: .\build.bat
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: chrome-temp.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
